### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by agtic** [Car85/neo_chronos_backend#1]
Sorry it's taken me so long to get to this @Car85. It's been a busy summer.

I had a few minutes and tried to install the backend.  I hit this error trying to pip install the requirements. Might be simple to troubleshoot,  but I ran out of time. I'll circle back on it in the next few days.

``` 
(env) (base) neo_chronos_backend % python -m venv env
(env) (base) neo_chronos_backend % source env/bin/activate
(env) (base) neo_chronos_backend % pip install -r requirements.txt
Collecting flask (from -r requirements.txt (line 1))
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
(env) (base)  neo_chronos_backend %

```

**Comment by Car85** [comment]
Hello @agtic thanks for the checking. I'm going to remove sqlite3 from the requeriments becouse Python have it by default, that's the reason of the error. Thanks again!

**Comment by Car85** [comment]
here is the commit: https://github.com/Car85/neo_chronos_backend/commit/17c83fa116fa0bc891f192d24be0f920d0ea7e26

**Comment by Car85** [comment]
Here is the new requeriments.txt file to avoid this error: https://github.com/Car85/neo_chronos_backend/commit/65d539d4093ce42c1bf3b7ab30aadec329724e68
